package IfoodTest;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

public class IfoodTest {
    private WebDriver driver;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\libs\\chromedriver.exe");
        driver = new ChromeDriver();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test


    public void testDeCadastro() {

        // 1 | open | /ifood-beneficios |
        driver.get("https://empresas.ifood.com.br/ifood-beneficios");

        // 2 | setWindowSize |
        driver.manage().window().maximize();

        // 3 | click | name=name |
        driver.findElement(By.name("name")).click();

        // 4 | type | name=name | Paulo
        driver.findElement(By.name("name")).sendKeys("Paulo Farias Guedes");

        // 5 | type | name=tel | (21)982736536
        driver.findElement(By.name("tel")).sendKeys("21982736536");

        // 6 | type | name=email | asdjhsdiduf@gmail.com
        driver.findElement(By.name("email")).sendKeys("asdjhsdiduf@gmail.com");

        // 7 | type | name=name-emp | akhs boladão
        driver.findElement(By.name("name-emp")).sendKeys("Fantastic Foods");

        // 8 | type | name=employees | 34
        driver.findElement(By.name("employees")).sendKeys("34");

        // 9 | click | name=cnpj |
        driver.findElement(By.name("cnpj")).click();

        // 10 | type | name=cnpj | 34.628.374/6238-47
        driver.findElement(By.name("cnpj")).sendKeys("27068131000167");

        // 11 | click | id=delivery-option |
        driver.findElement(By.id("delivery-option")).click();

        // 12 | select | id=delivery-option | label=Sim
        {
            WebElement dropdown = driver.findElement(By.id("delivery-option"));
            dropdown.findElement(By.xpath("//option[. = 'Sim']")).click();
        }

        // 13 | sleep | for 3 secs to check values
        //try{Thread.sleep(5000);}catch(InterruptedException ie){}

        // 14 | click | css=.contact-form-submit |
        driver.findElement(By.cssSelector(".contact-form-submit")).click();

        // 15 | assert | check if the thank you page message show up |
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".contact-return-title"));
            assert(elements.size() > 0);
        }

    }
}
